language: android
jdk: oraclejdk8

android:
  components:
    - android-22
    - sys-img-x86-android-22
  licenses:
    - 'android-sdk-license-.+'

before_script:
    - echo no | android create avd --force -n test -t android-22 --abi google_apis/x86
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator


script:
    - travis_retry ./gradlew build :androidformenhancer:connectedCheck

